export const GET_PRESENTATIONS = {
  REQUEST: "GET_PRESENTATIONS_REQUEST",
  SUCCESS: "GET_PRESENTATIONS_SUCCESS",
  FAIL: "GET_PRESENTATIONS_FAIL"
};

export const CREATE_PRESENTATION = {
  REQUEST: "CRATE_PRESENTATION_REQUEST",
  SUCCESS: "CRATE_PRESENTATION_SUCCESS",
  FAIL: "CRATE_PRESENTATION_FAIL"
};

export const ENTER_ROOM = {
  REQUEST: "ENTER_ROOM_REQUEST",
  SUCCESS: "ENTER_ROOM_SUCCESS",
  FAIL: "ENTER_ROOM_FAIL"
};
