export const GET_PRESENTATIONS = {
  REQUEST: "GET_PRESENTATIONS_REQUEST",
  SUCCESS: "GET_PRESENTATIONS_SUCCESS",
  FAIL: "GET_PRESENTATIONS_FAIL"
};

export const CREATE_PRESENTATION = {
  REQUEST: "CREATE_PRESENTATION_REQUEST",
  SUCCESS: "CREATE_PRESENTATION_SUCCESS",
  FAIL: "CREATE_PRESENTATION_FAIL"
};

export const CREATE_QUESTION = {
  REQUEST: "CREATE_QUESTION_REQUEST",
  SUCCESS: "CREATE_QUESTION_SUCCESS",
  FAIL: "CREATE_QUESTION_FAIL"
};
